import React, { createContext, useContext, useState, useEffect } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Nav
    discover: 'Discover',
    match: 'Match Finder',
    workflows: 'Workflows',
    detector: 'AI Detector',
    compare: 'Compare',
    prompts: 'Prompts',
    quiz: 'AI Quiz',
    academy: 'AI Academy',
    news: 'News & Blog',
    dashboard: 'Dashboard',
    admin: 'Admin',
    savedTools: 'Saved Tools',
    searchPlaceholder: 'Search 500+ AI tools, models, prompts...',
    login: 'Log In',
    signup: 'Sign Up',
    logout: 'Log Out',
    myDashboard: 'My Dashboard',
    quickTasks: 'Quick Task Search',
    selectLanguage: 'Select Language',
    signIn: 'Sign In',
    
    // Categories & Sections
    categories: 'Categories',
    specializedHubs: 'Specialized Hubs',
    showLess: 'Show Less',
    viewAllCategories: 'View All Categories',
    allTools: 'All Tools',
    tools: 'Tools',
    tool: 'Tool',
    sort: 'Sort:',
    trending: 'Trending',
    mostVisited: 'Most Visited',
    highestRated: 'Highest Rated',
    newest: 'Newest',
    recentlyUpdated: 'Recently Updated',
    pricingModel: 'Pricing Model',
    supportedPlatforms: 'Supported Platforms',
    capabilitiesLicensing: 'Capabilities & Licensing',
    apiAvailable: 'API Available',
    openSource: 'Open Source',
    commercialLicense: 'Commercial License',
    filter: 'Filter',
    showing: 'Showing',
    matchingTools: 'matching AI tools',
    in: 'in',
    verified: 'Verified Official AI Tool',
    saveTool: 'Save tool',
    saved: 'Saved',
    views: 'views',
    viewDetails: 'View details',

    // App Body & Grid
    discoverAiTools: 'Discover AI Tools',
    toolsAvailable: 'tools available',
    noToolsMatched: 'No AI tools matched your specific search criteria.',
    resetAllFilters: 'Reset All Filters',
    loadMoreAiTools: 'Load More AI Tools',
    remaining: 'remaining',
    of: 'of',
    addToolToCompare: 'Add Tool to Compare',
    sideBySideMatrix: 'Side-by-Side Matrix Engine',
    aiToolComparison: 'AI Tool Comparison Engine',
    comparisonDesc: 'Compare features, pricing, speed, accuracy, API support, and platform availability side-by-side.',
    promptsFound: 'Prompts Found',
    searchPromptsPlaceholder: 'Search by keyword, model, tag, or topic...',
    featured: 'Featured',
    all: 'All',
    liveNewsStream: 'LIVE AI NEWS STREAM',
    autoUpdatingIn: 'Auto-updating in',
    pauseAutoSync: 'Pause Live Stream',
    resumeAutoSync: 'Resume Live Stream',
    fetchLatestNews: 'Fetch Latest News',
    newsAutoUpdated: 'News auto-updated with fresh AI breakthroughs!',

    // Category Names
    Writing: 'Writing',
    'Image Generation': 'Image Generation',
    'Video Creation': 'Video Creation',
    Music: 'Music',
    Audio: 'Audio',
    Coding: 'Coding',
    Marketing: 'Marketing',
    Design: 'Design',
    Productivity: 'Productivity',
    Education: 'Education',
    Business: 'Business',
    Finance: 'Finance',
    Healthcare: 'Healthcare',
    Legal: 'Legal',
    Research: 'Research',
    'Data Analysis': 'Data Analysis',
    Automation: 'Automation',
    SEO: 'SEO',
    'Social Media': 'Social Media',
    Chatbots: 'Chatbots',
    Translation: 'Translation',
    Voice: 'Voice',
    '3D': '3D',
    Architecture: 'Architecture',
    Gaming: 'Gaming',
    'E-commerce': 'E-commerce',
    'Customer Support': 'Customer Support',
    Cybersecurity: 'Cybersecurity',
    HR: 'HR',
    Sales: 'Sales',

    // Pricing
    Free: 'Free',
    Freemium: 'Freemium',
    Paid: 'Paid',
    Enterprise: 'Enterprise',
    'Open Source': 'Open Source',

    // Platforms
    'Browser Based': 'Browser Based',
    Windows: 'Windows',
    macOS: 'macOS',
    Linux: 'Linux',
    Android: 'Android',
    iOS: 'iOS',
    'Chrome Extension': 'Chrome Extension',

    // Hero
    heroBadge: "The World's #1 AI Directory",
    heroTitle1: "Discover & Master the Best",
    heroTitle2: "AI Tools for Any Task",
    heroSubtitle: "Explore 500+ verified AI models, tools, prompts, and automated workflows to supercharge your productivity.",
    findMyMatch: "Find My Match",
    buildWorkflow: "Build Workflow",
    trendingTools: "Trending AI Tools",

    // Detector
    detectorBadge: "Powered by Advanced Gemini Analysis",
    detectorTitle: "AI Content Detector & Essay Checker",
    detectorSubtitle: "Accurately evaluate essays, ChatGPT responses, and AI articles with 100% precision scoring, inline highlighting, and an integrated AI Humanizer.",
    sourceText: "Source Text",
    academicEssay: "Academic Essay",
    articleBlog: "Article / Blog",
    codeTechnical: "Code & Technical",
    textareaPlaceholder: "Paste or type any essay, assignment, paper, or AI text here...",
    quickPresets: "Quick Presets:",
    detectAiButton: "Detect AI",
    scanning: "Scanning...",
    verdict: "Detection Verdict",
    aiProbability: "AI Probability",
    overview: "Overview",
    highlightCanvas: "Highlight Canvas",
    humanizeAi: "Humanize AI",
    readability: "Readability",
    perplexity: "Perplexity",
    burstiness: "Burstiness",
    clear: "Clear",
    copy: "Copy",
    copied: "Copied",

    // Footer
    footerDesc: "Your all-in-one portal for finding, comparing, and mastering artificial intelligence tools.",
    quickLinks: "Quick Links",
    allRightsReserved: "All rights reserved."
  },
  am: {
    // Nav (Amharic)
    discover: 'ግኝት',
    match: 'መሣሪያ ፈላጊ',
    workflows: 'የሥራ ፍሰት',
    detector: 'አይአይ መመርመሪያ',
    compare: 'ማወዳደሪያ',
    prompts: 'መመሪያዎች',
    quiz: 'ፈተና',
    academy: 'ትምህርት ቤት',
    news: 'ዜና እና ብሎግ',
    dashboard: 'ዳሽቦርድ',
    admin: 'አስተዳዳሪ',
    savedTools: 'የተቀመጡ መሣሪያዎች',
    searchPlaceholder: 'ከ500+ በላይ የአይአይ መሣሪያዎችን ይፈልጉ...',
    login: 'ግባ',
    signup: 'ተመዝገብ',
    logout: 'ውጣ',
    myDashboard: 'የኔ ዳሽቦርድ',
    quickTasks: 'ፈጣን ፍለጋ',
    selectLanguage: 'ቋንቋ ይምረጡ',
    signIn: 'ግባ',

    // Categories & Sections
    categories: 'ምድቦች',
    specializedHubs: 'የተለዩ ማዕከላት',
    showLess: 'በትንሹ አሳይ',
    viewAllCategories: 'ሁሉንም ምድቦች ይመልከቱ',
    allTools: 'ሁሉንም መሣሪያዎች',
    tools: 'መሣሪያዎች',
    tool: 'መሣሪያ',
    sort: 'ደርድር:',
    trending: 'በብዛት የሚወደዱ',
    mostVisited: 'በብዛት የተጎበኙ',
    highestRated: 'ከፍተኛ ደረጃ ያላቸው',
    newest: 'አዲስ የገቡ',
    recentlyUpdated: 'በቅርብ ጊዜ የተሻሻሉ',
    pricingModel: 'የዋጋ ዓይነት',
    supportedPlatforms: 'የሚደገፉ ፕላትፎርሞች',
    capabilitiesLicensing: 'ችሎታዎች እና ፈቃዶች',
    apiAvailable: 'ኤፒአይ (API) ያለው',
    openSource: 'ኦፕን ሶርስ (Open Source)',
    commercialLicense: 'የንግድ ፈቃድ',
    filter: 'ማጣሪያ',
    showing: 'በማሳየት ላይ',
    matchingTools: 'የተገኙ የአይአይ መሣሪያዎች',
    in: 'በ',
    verified: 'የተረጋገጠ ይፋዊ የአይአይ መሣሪያ',
    saveTool: 'መሣሪያ አስቀምጥ',
    saved: 'ተቀምጧል',
    views: 'ዕይታዎች',
    viewDetails: 'ዝርዝር ይመልከቱ',

    // App Body & Grid (Amharic)
    discoverAiTools: 'የአይአይ መሣሪያዎችን ያግኙ',
    toolsAvailable: 'መሣሪያዎች ይገኛሉ',
    noToolsMatched: 'ለፍለጋዎ የሚሆን የአይአይ መሣሪያ አልተገኘም።',
    resetAllFilters: 'ሁሉንም ማጣሪያዎች መልስ',
    loadMoreAiTools: 'ተጨማሪ የአይአይ መሣሪያዎችን አሳይ',
    remaining: 'ቀሪ',
    of: 'ከ',
    addToolToCompare: 'ለማወዳደር መሣሪያ ጨምር',
    sideBySideMatrix: 'ጎን ለጎን ማወዳደሪያ',
    aiToolComparison: 'የአይአይ መሣሪያዎች ማወዳደሪያ',
    comparisonDesc: 'የመሣሪያዎችን ባህሪያት፣ ዋጋ፣ ፍጥነት፣ ትክክለኛነት እና ኤፒአይ ጎን ለጎን ያወዳድሩ።',
    promptsFound: 'መመሪያዎች ተገኝተዋል',
    searchPromptsPlaceholder: 'በቁልፍ ቃል፣ ሞዴል ወይም ርዕስ ይፈልጉ...',
    featured: 'የተመረጡ',
    all: 'ሁሉም',

    // Category Names (Amharic)
    Writing: 'ጽሑፍ',
    'Image Generation': 'ምስል ፈጠራ',
    'Video Creation': 'ቪዲዮ ፈጠራ',
    Music: 'ሙዚቃ',
    Audio: 'ድምፅ',
    Coding: 'ኮዲንግ',
    Marketing: 'ማርኬቲንግ',
    Design: 'ዲዛይን',
    Productivity: 'ምርታማነት',
    Education: 'ትምህርት',
    Business: 'ንግድ',
    Finance: 'ፋይናንስ',
    Healthcare: 'ጤና',
    Legal: 'ሕግ',
    Research: 'ምርምር',
    'Data Analysis': 'ዳታ አናሊሲስ',
    Automation: 'ኦቶሜሽን',
    SEO: 'ኤስ.ኢ.ኦ (SEO)',
    'Social Media': 'ሶሻል ሚዲያ',
    Chatbots: 'ቻትቦቶች',
    Translation: 'ትርጉም',
    Voice: 'የድምፅ ሌሊት',
    '3D': '3D',
    Architecture: 'አርክቴክቸር',
    Gaming: 'ጌሚንግ',
    'E-commerce': 'ኢ-ኮመርስ',
    'Customer Support': 'ደንበኛ ድጋፍ',
    Cybersecurity: 'ሳይበር ደህንነት',
    HR: 'የሰው ኃይል',
    Sales: 'ሽያጭ',

    // Pricing (Amharic)
    Free: 'ነፃ',
    Freemium: 'ከፊል ነፃ',
    Paid: 'ክፍያ ያለው',
    Enterprise: 'ለድርጅቶች',
    'Open Source': 'ኦፕን ሶርስ',

    // Platforms (Amharic)
    'Browser Based': 'በብራውዘር የሚሰራ',
    Windows: 'ዊንዶውስ',
    macOS: 'ማክ (macOS)',
    Linux: 'ሊኑክስ',
    Android: 'አንድሮይድ',
    iOS: 'አይኦኤስ (iOS)',
    'Chrome Extension': 'የክሮም ማራዘሚያ',

    // Hero
    heroBadge: "የዓለማችን #1 የአይአይ መሣሪያዎች ማዕከል",
    heroTitle1: "ምርጥ የአይአይ መሣሪያዎችን",
    heroTitle2: "ያግኙ እና በጥራት ይጠቀሙ",
    heroSubtitle: "ስራዎን ለማቃለል ከ500+ በላይ የተረጋገጡ የአይአይ መሣሪያዎችን፣ መመሪያዎችን እና የሥራ ፍሰቶችን ይመልከቱ።",
    findMyMatch: "መሣሪያ ፈልግልኝ",
    buildWorkflow: "የሥራ ፍሰት ፍጠር",
    trendingTools: "በብዛት የሚፈለጉ መሣሪያዎች",

    // Detector
    detectorBadge: "በከፍተኛ ጄሚኒ አርቴፊሻል ኢንቴሊጀንስ የተደገፈ",
    detectorTitle: "የአይአይ ጽሑፍ መመርመሪያ እና ድርሰት ማረሚያ",
    detectorSubtitle: "በአይአይ፣ በካቲጂፒቲ እና ክሎድ የተጻፉ ድርሰቶችን እና ጽሑፎችን በ100% ትክክለኛነት ይመርምሩ እና ያስረዱ።",
    sourceText: "ምንጭ ጽሑፍ",
    academicEssay: "ትምህርታዊ ድርሰት",
    articleBlog: "ጽሑፍ / ብሎግ",
    codeTechnical: "ኮድ እና ቴክኒካል",
    textareaPlaceholder: "ማንኛውንም ድርሰት፣ የቤት ሥራ ወይም የአይአይ ጽሑፍ እዚህ ይለጥፉ...",
    quickPresets: "ምሳሌዎች:",
    detectAiButton: "አይአይ መርምር",
    scanning: "በመመርመር ላይ...",
    verdict: "የምርመራ ውጤት",
    aiProbability: "የአይአይ እድል",
    overview: "አጠቃላይ እይታ",
    highlightCanvas: "ማድመቂያ",
    humanizeAi: "ወደ ሰው አጻጻፍ ቀይር",
    readability: "የንባብ ቀላልነት",
    perplexity: "የቃላት ውስብስብነት",
    burstiness: "የዓረፍተ ነገር ልዩነት",
    clear: "አጽዳ",
    copy: "ቅዳ",
    copied: "ተቀድቷል",

    // Footer
    footerDesc: "የአርቴፊሻል ኢንቴሊጀንስ መሣሪያዎችን ለማግኘት፣ ለማወዳደር እና ለመማር የእርስዎ ዋና ማዕከል።",
    quickLinks: "ፈጣን አገናኞች",
    allRightsReserved: "መብቱ በህግ የተጠበቀ ነው።"
  },
  es: {
    discover: 'Descubrir',
    match: 'Buscador',
    workflows: 'Flujos de trabajo',
    detector: 'Detector IA',
    compare: 'Comparar',
    prompts: 'Prompts',
    quiz: 'Cuestionario IA',
    academy: 'Academia',
    news: 'Noticias y Blog',
    dashboard: 'Panel',
    admin: 'Admin',
    savedTools: 'Herramientas guardadas',
    searchPlaceholder: 'Buscar 500+ herramientas IA...',
    login: 'Iniciar sesión',
    signup: 'Registrarse',
    logout: 'Cerrar sesión',
    myDashboard: 'Mi Panel',
    quickTasks: 'Búsqueda rápida',
    selectLanguage: 'Seleccionar idioma',

    heroBadge: "El directorio de IA #1 del mundo",
    heroTitle1: "Descubre y domina las mejores",
    heroTitle2: "Herramientas de IA para cualquier tarea",
    heroSubtitle: "Explora más de 500 modelos, herramientas, prompts y flujos de trabajo de IA verificados.",
    findMyMatch: "Buscar mi herramienta",
    buildWorkflow: "Crear flujo de trabajo",
    trendingTools: "Herramientas populares",
    viewAllCategories: "Ver todas las categorías",

    detectorBadge: "Impulsado por análisis avanzado Gemini",
    detectorTitle: "Detector de Contenido IA y Verificador",
    detectorSubtitle: "Evalúa ensayos, respuestas de ChatGPT y artículos de IA con 100% de precisión.",
    sourceText: "Texto fuente",
    academicEssay: "Ensayo académico",
    articleBlog: "Artículo / Blog",
    codeTechnical: "Código y técnico",
    textareaPlaceholder: "Pega o escribe cualquier ensayo o texto de IA aquí...",
    quickPresets: "Muestras:",
    detectAiButton: "Detectar IA",
    scanning: "Escaneando...",
    verdict: "Veredicto",
    aiProbability: "Probabilidad IA",
    overview: "Resumen",
    highlightCanvas: "Resaltar lienzo",
    humanizeAi: "Humanizar IA",
    readability: "Legibilidad",
    perplexity: "Perplejidad",
    burstiness: "Variabilidad",
    clear: "Limpiar",
    copy: "Copiar",
    copied: "Copiado",

    footerDesc: "Tu portal integral para encontrar, comparar y dominar herramientas de IA.",
    quickLinks: "Enlaces rápidos",
    categories: "Categorías",
    allRightsReserved: "Todos los derechos reservados."
  },
  fr: {
    discover: 'Découvrir',
    match: 'Trouver un outil',
    workflows: 'Flux de travail',
    detector: 'Détecteur IA',
    compare: 'Comparer',
    prompts: 'Prompts',
    quiz: 'Quiz IA',
    academy: 'Académie',
    news: 'Actualités & Blog',
    dashboard: 'Tableau de bord',
    admin: 'Admin',
    savedTools: 'Outils sauvegardés',
    searchPlaceholder: 'Rechercher plus de 500 outils IA...',
    login: 'Connexion',
    signup: "S'inscrire",
    logout: 'Déconnexion',
    myDashboard: 'Mon Tableau de bord',
    quickTasks: 'Recherche rapide',
    selectLanguage: 'Choisir la langue',

    heroBadge: "Le répertoire d'IA #1 mondial",
    heroTitle1: "Découvrez et maîtrisez les meilleurs",
    heroTitle2: "Outils IA pour chaque tâche",
    heroSubtitle: "Explorez plus de 500 modèles, outils et flux de travail IA vérifiés.",
    findMyMatch: "Trouver mon outil",
    buildWorkflow: "Créer un flux",
    trendingTools: "Outils tendances",
    viewAllCategories: "Voir toutes les catégories",

    detectorBadge: "Propulsé par l'analyse Gemini",
    detectorTitle: "Détecteur de Contenu IA",
    detectorSubtitle: "Évaluez avec précision les essais, réponses ChatGPT et textes IA.",
    sourceText: "Texte source",
    academicEssay: "Dissertation académique",
    articleBlog: "Article / Blog",
    codeTechnical: "Code & Technique",
    textareaPlaceholder: "Collez votre texte IA ou dissertation ici...",
    quickPresets: "Exemples:",
    detectAiButton: "Détecter l'IA",
    scanning: "Analyse en cours...",
    verdict: "Verdict",
    aiProbability: "Probabilité IA",
    overview: "Aperçu",
    highlightCanvas: "Surlignage",
    humanizeAi: "Humaniser le texte",
    readability: "Lisibilité",
    perplexity: "Perplexité",
    burstiness: "Variabilité",
    clear: "Effacer",
    copy: "Copier",
    copied: "Copié",

    footerDesc: "Votre portail tout-en-un pour découvrir et maîtriser les outils d'IA.",
    quickLinks: "Liens rapides",
    categories: "Catégories",
    allRightsReserved: "Tous droits réservés."
  },
  de: {
    discover: 'Entdecken',
    match: 'KI-Finder',
    workflows: 'Workflows',
    detector: 'KI-Detektor',
    compare: 'Vergleichen',
    prompts: 'Prompts',
    quiz: 'KI-Quiz',
    academy: 'Akademie',
    news: 'News & Blog',
    dashboard: 'Dashboard',
    admin: 'Admin',
    savedTools: 'Gespeicherte Tools',
    searchPlaceholder: 'Über 500 KI-Tools suchen...',
    login: 'Anmelden',
    signup: 'Registrieren',
    logout: 'Abmelden',
    myDashboard: 'Mein Dashboard',
    quickTasks: 'Schnellsuche',
    selectLanguage: 'Sprache wählen',

    heroBadge: "Das weltweite #1 KI-Verzeichnis",
    heroTitle1: "Entdecken Sie die besten",
    heroTitle2: "KI-Tools für jede Aufgabe",
    heroSubtitle: "Erkunden Sie über 500 geprüfte KI-Modelle, Tools und automatisierte Workflows.",
    findMyMatch: "Passendes Tool finden",
    buildWorkflow: "Workflow erstellen",
    trendingTools: "Beliebte KI-Tools",
    viewAllCategories: "Alle Kategorien anzeigen",

    detectorBadge: "Angetrieben von moderner Gemini-Analyse",
    detectorTitle: "KI-Inhaltsdetektor & Prüfer",
    detectorSubtitle: "Prüfen Sie Aufsätze und ChatGPT-Texte präzise auf KI-Muster.",
    sourceText: "Quelltext",
    academicEssay: "Wissenschaftlicher Aufsatz",
    articleBlog: "Artikel / Blog",
    codeTechnical: "Code & Technisch",
    textareaPlaceholder: "Fügen Sie Aufsatz oder KI-Text hier ein...",
    quickPresets: "Beispiele:",
    detectAiButton: "KI erkennen",
    scanning: "Scannen...",
    verdict: "Ergebnis",
    aiProbability: "KI-Wahrscheinlichkeit",
    overview: "Übersicht",
    highlightCanvas: "Text hervorheben",
    humanizeAi: "KI vertraulicher machen",
    readability: "Lesbarkeit",
    perplexity: "Perplexität",
    burstiness: "Varianz",
    clear: "Löschen",
    copy: "Kopieren",
    copied: "Kopiert",

    footerDesc: "Ihr All-in-One-Portal zum Suchen, Vergleichen und Erlernen von KI-Tools.",
    quickLinks: "Direktlinks",
    categories: "Kategorien",
    allRightsReserved: "Alle Rechte vorbehalten."
  },
  zh: {
    discover: '发现',
    match: '匹配神器',
    workflows: '工作流',
    detector: 'AI 检测器',
    compare: '工具对比',
    prompts: '提示词库',
    quiz: 'AI 测验',
    academy: '学院',
    news: '新闻与博客',
    dashboard: '控制台',
    admin: '管理员',
    savedTools: '已保存工具',
    searchPlaceholder: '搜索 500+ 个 AI 工具、模型...',
    login: '登录',
    signup: '注册',
    logout: '退出登录',
    myDashboard: '我的控制台',
    quickTasks: '快速任务搜索',
    selectLanguage: '选择语言',

    heroBadge: "全球排名 #1 的 AI 工具目录",
    heroTitle1: "探索并掌握顶尖",
    heroTitle2: "适用于各类任务的 AI 工具",
    heroSubtitle: "探索 500+ 个经过验证的 AI 模型、提示词和自动化工作流。",
    findMyMatch: "寻找适合我的 AI",
    buildWorkflow: "构建工作流",
    trendingTools: "热门 AI 工具",
    viewAllCategories: "查看所有分类",

    detectorBadge: "基于 Advanced Gemini 引擎",
    detectorTitle: "AI 内容检测与论文检查器",
    detectorSubtitle: "高精度检测论文、ChatGPT 回复和 AI 生成的文章。",
    sourceText: "源码文本",
    academicEssay: "学术论文",
    articleBlog: "文章 / 博客",
    codeTechnical: "代码与技术",
    textareaPlaceholder: "在这里粘贴或输入论文、作业或 AI 文本...",
    quickPresets: "快捷预设:",
    detectAiButton: "检测 AI",
    scanning: "深度扫描中...",
    verdict: "检测判定",
    aiProbability: "AI 概率",
    overview: "概览",
    highlightCanvas: "高亮画布",
    humanizeAi: "人性化润色",
    readability: "可读性",
    perplexity: "困惑度",
    burstiness: "突发性",
    clear: "清空",
    copy: "复制",
    copied: "已复制",

    footerDesc: "您一站式查找、对比和掌握人工智能工具的专业门户。",
    quickLinks: "快速链接",
    categories: "分类",
    allRightsReserved: "保留所有权利。"
  },
  ja: {
    discover: '発見',
    match: 'AIマッチ器',
    workflows: 'ワークフロー',
    detector: 'AIチェッカー',
    compare: 'AI比較',
    prompts: 'プロンプト',
    quiz: 'AI診断',
    academy: 'アカデミー',
    news: 'ニュース',
    dashboard: 'ダッシュボード',
    admin: '管理者',
    savedTools: '保存したツール',
    searchPlaceholder: '500以上のAIツールを検索...',
    login: 'ログイン',
    signup: '新規登録',
    logout: 'ログアウト',
    myDashboard: 'マイページ',
    quickTasks: 'クイック検索',
    selectLanguage: '言語を選択',

    heroBadge: "世界No.1 AIツールディレクトリ",
    heroTitle1: "最高のAIツールを",
    heroTitle2: "発見して使いこなそう",
    heroSubtitle: "500以上の検証済みAIモデル、プロンプト、ワークフローを探索できます。",
    findMyMatch: "AI診断スタート",
    buildWorkflow: "ワークフロー作成",
    trendingTools: "トレンドAIツール",
    viewAllCategories: "全カテゴリーを見る",

    detectorBadge: "Gemini AIエンジン搭載",
    detectorTitle: "AI文章判定 & 論文チェッカー",
    detectorSubtitle: "ChatGPTやAI生成文章、論文を高精度に判定します。",
    sourceText: "解析テキスト",
    academicEssay: "学術論文",
    articleBlog: "記事 / ブログ",
    codeTechnical: "コード & 技術文書",
    textareaPlaceholder: "論文やAI生成文章をここに貼り付けてください...",
    quickPresets: "サンプル:",
    detectAiButton: "AI判定を実行",
    scanning: "解析中...",
    verdict: "判定結果",
    aiProbability: "AI生成確率",
    overview: "概要",
    highlightCanvas: "ハイライト表示",
    humanizeAi: "自然な文章に変換",
    readability: "読みやすさ",
    perplexity: "複雑度",
    burstiness: "バースト性",
    clear: "消去",
    copy: "コピー",
    copied: "コピー完了",

    footerDesc: "AIツールの検索・比較・学習がこれ一つで完結する総合ポータル。",
    quickLinks: "クイックリンク",
    categories: "カテゴリー",
    allRightsReserved: "All rights reserved."
  },
  pt: {
    discover: 'Descobrir',
    match: 'Localizador',
    workflows: 'Fluxos de trabalho',
    detector: 'Detector de IA',
    compare: 'Comparar',
    prompts: 'Prompts',
    quiz: 'Quiz de IA',
    academy: 'Academia',
    news: 'Notícias & Blog',
    dashboard: 'Painel',
    admin: 'Admin',
    savedTools: 'Ferramentas salvas',
    searchPlaceholder: 'Pesquisar +500 ferramentas de IA...',
    login: 'Entrar',
    signup: 'Cadastrar',
    logout: 'Sair',
    myDashboard: 'Meu Painel',
    quickTasks: 'Busca rápida',
    selectLanguage: 'Selecionar idioma',

    heroBadge: "O diretório de IA nº 1 do mundo",
    heroTitle1: "Descubra e domine as melhores",
    heroTitle2: "Ferramentas de IA para qualquer tarefa",
    heroSubtitle: "Explore mais de 500 modelos, ferramentas e fluxos de trabalho de IA verificados.",
    findMyMatch: "Encontrar minha IA",
    buildWorkflow: "Criar fluxo",
    trendingTools: "Ferramentas em alta",
    viewAllCategories: "Ver todas as categorias",

    detectorBadge: "Com tecnologia avançada Gemini",
    detectorTitle: "Detector de Conteúdo de IA e Ensaios",
    detectorSubtitle: "Avalie ensaios, respostas do ChatGPT e textos de IA com alta precisão.",
    sourceText: "Texto fonte",
    academicEssay: "Ensaio acadêmico",
    articleBlog: "Artigo / Blog",
    codeTechnical: "Código e técnico",
    textareaPlaceholder: "Cole seu texto ou ensaio de IA aqui...",
    quickPresets: "Exemplos:",
    detectAiButton: "Detectar IA",
    scanning: "Analisando...",
    verdict: "Veredito",
    aiProbability: "Probabilidade de IA",
    overview: "Visão geral",
    highlightCanvas: "Destacar texto",
    humanizeAi: "Humanizar texto",
    readability: "Legibilidade",
    perplexity: "Perplexidade",
    burstiness: "Variância",
    clear: "Limpar",
    copy: "Copiar",
    copied: "Copiado",

    footerDesc: "Seu portal completo para encontrar, comparar e dominar ferramentas de IA.",
    quickLinks: "Links rápidos",
    categories: "Categorias",
    allRightsReserved: "Todos os direitos reservados."
  },
  ru: {
    discover: 'Обзор',
    match: 'Подбор ИИ',
    workflows: 'Сценарии',
    detector: 'Детектор ИИ',
    compare: 'Сравнение',
    prompts: 'Промпты',
    quiz: 'ИИ-Тест',
    academy: 'Академия',
    news: 'Новости и Блог',
    dashboard: 'Кабинет',
    admin: 'Админ',
    savedTools: 'Сохраненные сервисы',
    searchPlaceholder: 'Поиск 500+ ИИ-инструментов...',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    myDashboard: 'Мой Кабинет',
    quickTasks: 'Быстрый поиск',
    selectLanguage: 'Выберите язык',

    heroBadge: "Каталог ИИ-инструментов №1 в мире",
    heroTitle1: "Находите и осваивайте лучшие",
    heroTitle2: "ИИ-сервисы для любых задач",
    heroSubtitle: "Более 500 проверенных ИИ-моделей, промптов и автоматизированных сценариев.",
    findMyMatch: "Подобрать ИИ",
    buildWorkflow: "Создать сценарий",
    trendingTools: "Популярные сервисы",
    viewAllCategories: "Все категории",

    detectorBadge: "На базе технологий Gemini",
    detectorTitle: "Детектор ИИ-текста и Проверка Статей",
    detectorSubtitle: "Высокоточный анализ эссе, ответов ChatGPT и сгенерированных текстов.",
    sourceText: "Исходный текст",
    academicEssay: "Академическое эссе",
    articleBlog: "Статья / Блог",
    codeTechnical: "Код и спецификации",
    textareaPlaceholder: "Вставьте эссе или ИИ-текст здесь...",
    quickPresets: "Образцы:",
    detectAiButton: "Проверить текст",
    scanning: "Сканирование...",
    verdict: "Результат",
    aiProbability: "Вероятность ИИ",
    overview: "Обзор",
    highlightCanvas: "Подсветка фрагментов",
    humanizeAi: "Очеловечить текст",
    readability: "Читаемость",
    perplexity: "Перплексия",
    burstiness: "Вариативность",
    clear: "Очистить",
    copy: "Копировать",
    copied: "Скопировано",

    footerDesc: "Ваш единый портал для поиска, сравнения и изучения искусственного интеллекта.",
    quickLinks: "Быстрые ссылки",
    categories: "Категории",
    allRightsReserved: "Все права защищены."
  },
  ar: {
    discover: 'استكشاف',
    match: 'مُطابق الذكاء الاصطناعي',
    workflows: 'مسارات العمل',
    detector: 'كاشف الذكاء الاصطناعي',
    compare: 'مقارنة',
    prompts: 'الأوامر (Prompts)',
    quiz: 'اختبار الذكاء الاصطناعي',
    academy: 'الأكاديمية',
    news: 'الأخبار والمدونة',
    dashboard: 'لوحة التحكم',
    admin: 'المشرف',
    savedTools: 'الأدوات المحفوظة',
    searchPlaceholder: 'ابحث في أكثر من 500 أداة ذكاء اصطناعي...',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    myDashboard: 'لوحتي الخاصة',
    quickTasks: 'بحث سريع',
    selectLanguage: 'اختر اللغة',

    heroBadge: "الدليل الأول عالمياً لأدوات الذكاء الاصطناعي",
    heroTitle1: "اكتشف واحترف أفضل",
    heroTitle2: "أدوات الذكاء الاصطناعي لكل مهامك",
    heroSubtitle: "استكشف أكثر من 500 نموذج وأداة ومسار عمل أوتوماتيكي مُتحقق منه.",
    findMyMatch: "اعثر على أداتي المناسبة",
    buildWorkflow: "إنشاء مسار عمل",
    trendingTools: "الأدوات الأكثر شعبية",
    viewAllCategories: "عرض كل التصنيفات",

    detectorBadge: "مدعوم بالتحليل المتقدم من Gemini",
    detectorTitle: "كاشف المحتوى المولد بالذكاء الاصطناعي",
    detectorSubtitle: "فحص دقيق للمقالات وإجابات ChatGPT والنصوص المولدة بدقة 100%.",
    sourceText: "النص الأصلي",
    academicEssay: "مقال أكاديمي",
    articleBlog: "مقال / مدونة",
    codeTechnical: "كود وبرمجيات",
    textareaPlaceholder: "الصق النص أو المقال المراد فحصه هنا...",
    quickPresets: "عينات تجريبية:",
    detectAiButton: "فحص النص",
    scanning: "جاري الفحص...",
    verdict: "النتيجة النهائية",
    aiProbability: "نسبة الذكاء الاصطناعي",
    overview: "نظرة عامة",
    highlightCanvas: "تظليل الجمل",
    humanizeAi: "تحويل النص إلى أسلوب بشري",
    readability: "سهولة القراءة",
    perplexity: "التعقيد اللغوي",
    burstiness: "تنوع الجمل",
    clear: "مسح",
    copy: "نسخ",
    copied: "تم النسخ",

    footerDesc: "بوابتك الشاملة لاكتشاف ومقارنة واحتراف أدوات الذكاء الاصطناعي.",
    quickLinks: "روابط سريعة",
    categories: "التصنيفات",
    allRightsReserved: "جميع الحقوق محفوظة."
  }
};

interface LanguageContextType {
  currentLang: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<Language>(() => {
    try {
      const savedCode = localStorage.getItem('aicentral_lang');
      const found = LANGUAGES.find(l => l.code === savedCode);
      if (found) return found;
    } catch (e) {
      console.warn('LocalStorage error:', e);
    }
    return LANGUAGES[0]; // English default
  });

  const setLanguage = (lang: Language) => {
    setCurrentLang(lang);
    try {
      localStorage.setItem('aicentral_lang', lang.code);
    } catch (e) {
      console.warn('LocalStorage save error:', e);
    }
  };

  const t = (key: string): string => {
    const langDictionary = TRANSLATIONS[currentLang.code];
    if (langDictionary && langDictionary[key]) {
      return langDictionary[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
